export const COUNTRY_CODES = [
  { code: "+91", name: "India", isoCode: "IN", flag: "🇮🇳" },
  { code: "+93", name: "Afghanistan", isoCode: "AF", flag: "🇦🇫" },
  { code: "+358", name: "Åland Islands", isoCode: "AX", flag: "🇦🇽" },
  { code: "+355", name: "Albania", isoCode: "AL", flag: "🇦🇱" },
  { code: "+213", name: "Algeria", isoCode: "DZ", flag: "🇩🇿" },
  { code: "+1684", name: "American Samoa", isoCode: "AS", flag: "🇦🇸" },
  { code: "+376", name: "Andorra", isoCode: "AD", flag: "🇦🇩" },
  { code: "+244", name: "Angola", isoCode: "AO", flag: "🇦🇴" },
  { code: "+1264", name: "Anguilla", isoCode: "AI", flag: "🇦🇮" },
  { code: "+672", name: "Antarctica", isoCode: "AQ", flag: "🇦🇶" },
  { code: "+1268", name: "Antigua and Barbuda", isoCode: "AG", flag: "🇦🇬" },
  { code: "+54", name: "Argentina", isoCode: "AR", flag: "🇦🇷" },
  { code: "+374", name: "Armenia", isoCode: "AM", flag: "🇦🇲" },
  { code: "+297", name: "Aruba", isoCode: "AW", flag: "🇦🇼" },
  { code: "+61", name: "Australia", isoCode: "AU", flag: "🇦🇺" },
  { code: "+43", name: "Austria", isoCode: "AT", flag: "🇦🇹" },
  { code: "+994", name: "Azerbaijan", isoCode: "AZ", flag: "🇦🇿" },
  { code: "+1242", name: "Bahamas", isoCode: "BS", flag: "🇧🇸" },
  { code: "+973", name: "Bahrain", isoCode: "BH", flag: "🇧🇭" },
  { code: "+880", name: "Bangladesh", isoCode: "BD", flag: "🇧🇩" },
  { code: "+1246", name: "Barbados", isoCode: "BB", flag: "🇧🇧" },
  { code: "+375", name: "Belarus", isoCode: "BY", flag: "🇧🇾" },
  { code: "+32", name: "Belgium", isoCode: "BE", flag: "🇧🇪" },
  { code: "+501", name: "Belize", isoCode: "BZ", flag: "🇧🇿" },
  { code: "+229", name: "Benin", isoCode: "BJ", flag: "🇧🇯" },
  { code: "+1441", name: "Bermuda", isoCode: "BM", flag: "🇧🇲" },
  { code: "+975", name: "Bhutan", isoCode: "BT", flag: "🇧🇹" },
  { code: "+591", name: "Bolivia", isoCode: "BO", flag: "🇧🇴" },
  { code: "+387", name: "Bosnia and Herzegovina", isoCode: "BA", flag: "🇧🇦" },
  { code: "+267", name: "Botswana", isoCode: "BW", flag: "🇧🇼" },
  { code: "+47", name: "Bouvet Island", isoCode: "BV", flag: "🏳" },
  { code: "+55", name: "Brazil", isoCode: "BR", flag: "🇧🇷" },
  { code: "+246", name: "British Indian Ocean Territory", isoCode: "IO", flag: "🇮🇴" },
  { code: "+673", name: "Brunei Darussalam", isoCode: "BN", flag: "🇧🇳" },
  { code: "+359", name: "Bulgaria", isoCode: "BG", flag: "🇧🇬" },
  { code: "+226", name: "Burkina Faso", isoCode: "BF", flag: "🇧🇫" },
  { code: "+257", name: "Burundi", isoCode: "BI", flag: "🇧🇮" },
  { code: "+855", name: "Cambodia", isoCode: "KH", flag: "🇰🇭" },
  { code: "+237", name: "Cameroon", isoCode: "CM", flag: "🇨🇲" },
  { code: "+1", name: "Canada", isoCode: "CA", flag: "🇨🇦" },
  { code: "+238", name: "Cape Verde", isoCode: "CV", flag: "🇨🇻" },
  { code: "+345", name: "Cayman Islands", isoCode: "KY", flag: "🇰🇾" },
  { code: "+236", name: "Central African Republic", isoCode: "CF", flag: "🇨🇫" },
  { code: "+235", name: "Chad", isoCode: "TD", flag: "🇹🇩" },
  { code: "+56", name: "Chile", isoCode: "CL", flag: "🇨🇱" },
  { code: "+86", name: "China", isoCode: "CN", flag: "🇨🇳" },
  { code: "+61", name: "Christmas Island", isoCode: "CX", flag: "🇨🇽" },
  { code: "+61", name: "Cocos (Keeling) Islands", isoCode: "CC", flag: "🇨🇨" },
  { code: "+57", name: "Colombia", isoCode: "CO", flag: "🇨🇴" },
  { code: "+269", name: "Comoros", isoCode: "KM", flag: "🇰🇲" },
  { code: "+242", name: "Congo", isoCode: "CG", flag: "🇨🇬" },
  { code: "+243", name: "Congo, Democratic Republic", isoCode: "CD", flag: "🇨🇩" },
  { code: "+682", name: "Cook Islands", isoCode: "CK", flag: "🇨🇰" },
  { code: "+506", name: "Costa Rica", isoCode: "CR", flag: "🇨🇷" },
  { code: "+225", name: "Cote d'Ivoire", isoCode: "CI", flag: "🇨🇮" },
  { code: "+385", name: "Croatia", isoCode: "HR", flag: "🇭🇷" },
  { code: "+53", name: "Cuba", isoCode: "CU", flag: "🇨🇺" },
  { code: "+357", name: "Cyprus", isoCode: "CY", flag: "🇨🇾" },
  { code: "+420", name: "Czech Republic", isoCode: "CZ", flag: "🇨🇿" },
  { code: "+45", name: "Denmark", isoCode: "DK", flag: "🇩🇰" },
  { code: "+253", name: "Djibouti", isoCode: "DJ", flag: "🇩🇯" },
  { code: "+1767", name: "Dominica", isoCode: "DM", flag: "🇩🇲" },
  { code: "+1849", name: "Dominican Republic", isoCode: "DO", flag: "🇩🇴" },
  { code: "+593", name: "Ecuador", isoCode: "EC", flag: "🇪🇨" },
  { code: "+20", name: "Egypt", isoCode: "EG", flag: "🇪🇬" },
  { code: "+503", name: "El Salvador", isoCode: "SV", flag: "🇸🇻" },
  { code: "+240", name: "Equatorial Guinea", isoCode: "GQ", flag: "🇬🇶" },
  { code: "+291", name: "Eritrea", isoCode: "ER", flag: "🇪🇷" },
  { code: "+372", name: "Estonia", isoCode: "EE", flag: "🇪🇪" },
  { code: "+251", name: "Ethiopia", isoCode: "ET", flag: "🇪🇹" },
  { code: "+500", name: "Falkland Islands", isoCode: "FK", flag: "🇫🇰" },
  { code: "+298", name: "Faroe Islands", isoCode: "FO", flag: "🇫🇴" },
  { code: "+679", name: "Fiji", isoCode: "FJ", flag: "🇫🇯" },
  { code: "+358", name: "Finland", isoCode: "FI", flag: "🇫🇮" },
  { code: "+33", name: "France", isoCode: "FR", flag: "🇫🇷" },
  { code: "+594", name: "French Guiana", isoCode: "GF", flag: "🇬🇫" },
  { code: "+689", name: "French Polynesia", isoCode: "PF", flag: "🇵🇫" },
  { code: "+262", name: "French Southern Territories", isoCode: "TF", flag: "🇹🇫" },
  { code: "+241", name: "Gabon", isoCode: "GA", flag: "🇬🇦" },
  { code: "+220", name: "Gambia", isoCode: "GM", flag: "🇬🇲" },
  { code: "+995", name: "Georgia", isoCode: "GE", flag: "🇬🇪" },
  { code: "+49", name: "Germany", isoCode: "DE", flag: "🇩🇪" },
  { code: "+233", name: "Ghana", isoCode: "GH", flag: "🇬🇭" },
  { code: "+350", name: "Gibraltar", isoCode: "GI", flag: "🇬🇮" },
  { code: "+30", name: "Greece", isoCode: "GR", flag: "🇬🇷" },
  { code: "+299", name: "Greenland", isoCode: "GL", flag: "🇬🇱" },
  { code: "+1473", name: "Grenada", isoCode: "GD", flag: "🇬🇩" },
  { code: "+590", name: "Guadeloupe", isoCode: "GP", flag: "🇬🇵" },
  { code: "+1671", name: "Guam", isoCode: "GU", flag: "🇬🇺" },
  { code: "+502", name: "Guatemala", isoCode: "GT", flag: "🇬🇹" },
  { code: "+44", name: "Guernsey", isoCode: "GG", flag: "🇬🇬" },
  { code: "+224", name: "Guinea", isoCode: "GN", flag: "🇬🇳" },
  { code: "+245", name: "Guinea-Bissau", isoCode: "GW", flag: "🇬🇼" },
  { code: "+592", name: "Guyana", isoCode: "GY", flag: "🇬🇾" },
  { code: "+509", name: "Haiti", isoCode: "HT", flag: "🇭🇹" },
  { code: "+379", name: "Holy See (Vatican City)", isoCode: "VA", flag: "🇻🇦" },
  { code: "+504", name: "Honduras", isoCode: "HN", flag: "🇭🇳" },
  { code: "+852", name: "Hong Kong", isoCode: "HK", flag: "🇭🇰" },
  { code: "+36", name: "Hungary", isoCode: "HU", flag: "🇭🇺" },
  { code: "+354", name: "Iceland", isoCode: "IS", flag: "🇮🇸" },
  { code: "+62", name: "Indonesia", isoCode: "ID", flag: "🇮🇩" },
  { code: "+98", name: "Iran", isoCode: "IR", flag: "🇮🇷" },
  { code: "+964", name: "Iraq", isoCode: "IQ", flag: "🇮🇶" },
  { code: "+353", name: "Ireland", isoCode: "IE", flag: "🇮🇪" },
  { code: "+44", name: "Isle of Man", isoCode: "IM", flag: "🇮🇲" },
  { code: "+972", name: "Israel", isoCode: "IL", flag: "🇮🇱" },
  { code: "+39", name: "Italy", isoCode: "IT", flag: "🇮🇹" },
  { code: "+1876", name: "Jamaica", isoCode: "JM", flag: "🇯🇲" },
  { code: "+81", name: "Japan", isoCode: "JP", flag: "🇯🇵" },
  { code: "+44", name: "Jersey", isoCode: "JE", flag: "🇯🇪" },
  { code: "+962", name: "Jordan", isoCode: "JO", flag: "🇯🇴" },
  { code: "+7", name: "Kazakhstan", isoCode: "KZ", flag: "🇰🇿" },
  { code: "+254", name: "Kenya", isoCode: "KE", flag: "🇰🇪" },
  { code: "+686", name: "Kiribati", isoCode: "KI", flag: "🇰🇮" },
  { code: "+850", name: "North Korea", isoCode: "KP", flag: "🇰🇵" },
  { code: "+82", name: "South Korea", isoCode: "KR", flag: "🇰🇷" },
  { code: "+383", name: "Kosovo", isoCode: "XK", flag: "🇽🇰" },
  { code: "+965", name: "Kuwait", isoCode: "KW", flag: "🇰🇼" },
  { code: "+996", name: "Kyrgyzstan", isoCode: "KG", flag: "🇰🇬" },
  { code: "+856", name: "Laos", isoCode: "LA", flag: "🇱🇦" },
  { code: "+371", name: "Latvia", isoCode: "LV", flag: "🇱🇻" },
  { code: "+961", name: "Lebanon", isoCode: "LB", flag: "🇱🇧" },
  { code: "+266", name: "Lesotho", isoCode: "LS", flag: "🇱🇸" },
  { code: "+231", name: "Liberia", isoCode: "LR", flag: "🇱🇷" },
  { code: "+218", name: "Libya", isoCode: "LY", flag: "🇱🇾" },
  { code: "+423", name: "Liechtenstein", isoCode: "LI", flag: "🇱🇮" },
  { code: "+370", name: "Lithuania", isoCode: "LT", flag: "🇱🇹" },
  { code: "+352", name: "Luxembourg", isoCode: "LU", flag: "🇱🇺" },
  { code: "+853", name: "Macao", isoCode: "MO", flag: "🇲🇴" },
  { code: "+389", name: "Macedonia", isoCode: "MK", flag: "🇲🇰" },
  { code: "+261", name: "Madagascar", isoCode: "MG", flag: "🇲🇬" },
  { code: "+265", name: "Malawi", isoCode: "MW", flag: "🇲🇼" },
  { code: "+60", name: "Malaysia", isoCode: "MY", flag: "🇲🇾" },
  { code: "+960", name: "Maldives", isoCode: "MV", flag: "🇲🇻" },
  { code: "+223", name: "Mali", isoCode: "ML", flag: "🇲🇱" },
  { code: "+356", name: "Malta", isoCode: "MT", flag: "🇲🇹" },
  { code: "+692", name: "Marshall Islands", isoCode: "MH", flag: "🇲🇭" },
  { code: "+596", name: "Martinique", isoCode: "MQ", flag: "🇲🇶" },
  { code: "+222", name: "Mauritania", isoCode: "MR", flag: "🇲🇷" },
  { code: "+230", name: "Mauritius", isoCode: "MU", flag: "🇲🇺" },
  { code: "+262", name: "Mayotte", isoCode: "YT", flag: "🇾🇹" },
  { code: "+52", name: "Mexico", isoCode: "MX", flag: "🇲🇽" },
  { code: "+691", name: "Micronesia", isoCode: "FM", flag: "🇫🇲" },
  { code: "+373", name: "Moldova", isoCode: "MD", flag: "🇲🇩" },
  { code: "+377", name: "Monaco", isoCode: "MC", flag: "🇲🇨" },
  { code: "+976", name: "Mongolia", isoCode: "MN", flag: "🇲🇳" },
  { code: "+382", name: "Montenegro", isoCode: "ME", flag: "🇲🇪" },
  { code: "+1664", name: "Montserrat", isoCode: "MS", flag: "🇲🇸" },
  { code: "+212", name: "Morocco", isoCode: "MA", flag: "🇲🇦" },
  { code: "+258", name: "Mozambique", isoCode: "MZ", flag: "🇲🇿" },
  { code: "+95", name: "Myanmar", isoCode: "MM", flag: "🇲🇲" },
  { code: "+264", name: "Namibia", isoCode: "NA", flag: "🇳🇦" },
  { code: "+674", name: "Nauru", isoCode: "NR", flag: "🇳🇷" },
  { code: "+977", name: "Nepal", isoCode: "NP", flag: "🇳🇵" },
  { code: "+31", name: "Netherlands", isoCode: "NL", flag: "🇳🇱" },
  { code: "+687", name: "New Caledonia", isoCode: "NC", flag: "🇳🇨" },
  { code: "+64", name: "New Zealand", isoCode: "NZ", flag: "🇳🇿" },
  { code: "+505", name: "Nicaragua", isoCode: "NI", flag: "🇳🇮" },
  { code: "+227", name: "Niger", isoCode: "NE", flag: "🇳🇪" },
  { code: "+234", name: "Nigeria", isoCode: "NG", flag: "🇳🇬" },
  { code: "+683", name: "Niue", isoCode: "NU", flag: "🇳🇺" },
  { code: "+672", name: "Norfolk Island", isoCode: "NF", flag: "🇳🇫" },
  { code: "+1670", name: "Northern Mariana Islands", isoCode: "MP", flag: "🏳" },
  { code: "+47", name: "Norway", isoCode: "NO", flag: "🇳🇴" },
  { code: "+968", name: "Oman", isoCode: "OM", flag: "🇴🇲" },
  { code: "+92", name: "Pakistan", isoCode: "PK", flag: "🇵🇰" },
  { code: "+680", name: "Palau", isoCode: "PW", flag: "🇵🇼" },
  { code: "+970", name: "Palestine", isoCode: "PS", flag: "🇵🇸" },
  { code: "+507", name: "Panama", isoCode: "PA", flag: "🇵🇦" },
  { code: "+675", name: "Papua New Guinea", isoCode: "PG", flag: "🇵🇬" },
  { code: "+595", name: "Paraguay", isoCode: "PY", flag: "🇵🇾" },
  { code: "+51", name: "Peru", isoCode: "PE", flag: "🇵🇪" },
  { code: "+63", name: "Philippines", isoCode: "PH", flag: "🇵🇭" },
  { code: "+64", name: "Pitcairn", isoCode: "PN", flag: "🇵🇳" },
  { code: "+48", name: "Poland", isoCode: "PL", flag: "🇵🇱" },
  { code: "+351", name: "Portugal", isoCode: "PT", flag: "🇵🇹" },
  { code: "+1939", name: "Puerto Rico", isoCode: "PR", flag: "🇵🇷" },
  { code: "+974", name: "Qatar", isoCode: "QA", flag: "🇶🇦" },
  { code: "+40", name: "Romania", isoCode: "RO", flag: "🇷🇴" },
  { code: "+7", name: "Russia", isoCode: "RU", flag: "🇷🇺" },
  { code: "+250", name: "Rwanda", isoCode: "RW", flag: "🇷🇼" },
  { code: "+262", name: "Reunion", isoCode: "RE", flag: "🇫🇷" },
  { code: "+590", name: "Saint Barthelemy", isoCode: "BL", flag: "🇧🇱" },
  { code: "+290", name: "Saint Helena", isoCode: "SH", flag: "🇸🇭" },
  { code: "+1869", name: "Saint Kitts and Nevis", isoCode: "KN", flag: "🇰🇳" },
  { code: "+1758", name: "Saint Lucia", isoCode: "LC", flag: "🇱🇨" },
  { code: "+590", name: "Saint Martin", isoCode: "MF", flag: "🏳" },
  { code: "+508", name: "Saint Pierre and Miquelon", isoCode: "PM", flag: "🇵🇲" },
  { code: "+1784", name: "Saint Vincent", isoCode: "VC", flag: "🇻🇨" },
  { code: "+685", name: "Samoa", isoCode: "WS", flag: "🇼🇸" },
  { code: "+378", name: "San Marino", isoCode: "SM", flag: "🇸🇲" },
  { code: "+239", name: "Sao Tome and Principe", isoCode: "ST", flag: "🇸🇹" },
  { code: "+966", name: "Saudi Arabia", isoCode: "SA", flag: "🇸🇦" },
  { code: "+221", name: "Senegal", isoCode: "SN", flag: "🇸🇳" },
  { code: "+381", name: "Serbia", isoCode: "RS", flag: "🇷🇸" },
  { code: "+248", name: "Seychelles", isoCode: "SC", flag: "🇸🇨" },
  { code: "+232", name: "Sierra Leone", isoCode: "SL", flag: "🇸🇱" },
  { code: "+65", name: "Singapore", isoCode: "SG", flag: "🇸🇬" },
  { code: "+421", name: "Slovakia", isoCode: "SK", flag: "🇸🇰" },
  { code: "+386", name: "Slovenia", isoCode: "SI", flag: "🇸🇮" },
  { code: "+677", name: "Solomon Islands", isoCode: "SB", flag: "🇸🇧" },
  { code: "+252", name: "Somalia", isoCode: "SO", flag: "🇸🇴" },
  { code: "+27", name: "South Africa", isoCode: "ZA", flag: "🇿🇦" },
  { code: "+211", name: "South Sudan", isoCode: "SS", flag: "🇸🇸" },
  { code: "+500", name: "South Georgia", isoCode: "GS", flag: "🇬🇸" },
  { code: "+34", name: "Spain", isoCode: "ES", flag: "🇪🇸" },
  { code: "+94", name: "Sri Lanka", isoCode: "LK", flag: "🇱🇰" },
  { code: "+249", name: "Sudan", isoCode: "SD", flag: "🇸🇩" },
  { code: "+597", name: "Suriname", isoCode: "SR", flag: "🇸🇷" },
  { code: "+47", name: "Svalbard and Jan Mayen", isoCode: "SJ", flag: "🇩🇰" },
  { code: "+268", name: "Swaziland", isoCode: "SZ", flag: "🇸🇿" },
  { code: "+46", name: "Sweden", isoCode: "SE", flag: "🇸🇪" },
  { code: "+41", name: "Switzerland", isoCode: "CH", flag: "🇨🇭" },
  { code: "+963", name: "Syria", isoCode: "SY", flag: "🇸🇾" },
  { code: "+886", name: "Taiwan", isoCode: "TW", flag: "🇹🇼" },
  { code: "+992", name: "Tajikistan", isoCode: "TJ", flag: "🇹🇯" },
  { code: "+255", name: "Tanzania", isoCode: "TZ", flag: "🇹🇿" },
  { code: "+66", name: "Thailand", isoCode: "TH", flag: "🇹🇭" },
  { code: "+670", name: "Timor-Leste", isoCode: "TL", flag: "🇹🇱" },
  { code: "+228", name: "Togo", isoCode: "TG", flag: "🇹🇬" },
  { code: "+690", name: "Tokelau", isoCode: "TK", flag: "🇹🇰" },
  { code: "+676", name: "Tonga", isoCode: "TO", flag: "🇹🇴" },
  { code: "+1868", name: "Trinidad and Tobago", isoCode: "TT", flag: "🇹🇹" },
  { code: "+216", name: "Tunisia", isoCode: "TN", flag: "🇹🇳" },
  { code: "+90", name: "Turkey", isoCode: "TR", flag: "🇹🇷" },
  { code: "+993", name: "Turkmenistan", isoCode: "TM", flag: "🇹🇲" },
  { code: "+1649", name: "Turks and Caicos Islands", isoCode: "TC", flag: "🇹🇨" },
  { code: "+688", name: "Tuvalu", isoCode: "TV", flag: "🇹🇻" },
  { code: "+256", name: "Uganda", isoCode: "UG", flag: "🇺🇬" },
  { code: "+380", name: "Ukraine", isoCode: "UA", flag: "🇺🇦" },
  { code: "+971", name: "United Arab Emirates", isoCode: "AE", flag: "🇦🇪" },
  { code: "+44", name: "United Kingdom", isoCode: "GB", flag: "🇬🇧" },
  { code: "+1", name: "United States", isoCode: "US", flag: "🇺🇸" },
  { code: "+598", name: "Uruguay", isoCode: "UY", flag: "🇺🇾" },
  { code: "+998", name: "Uzbekistan", isoCode: "UZ", flag: "🇺🇿" },
  { code: "+678", name: "Vanuatu", isoCode: "VU", flag: "🇻🇺" },
  { code: "+58", name: "Venezuela", isoCode: "VE", flag: "🇻🇪" },
  { code: "+84", name: "Vietnam", isoCode: "VN", flag: "🇻🇳" },
  { code: "+1284", name: "Virgin Islands, British", isoCode: "VG", flag: "🇻🇬" },
  { code: "+1340", name: "Virgin Islands, U.S.", isoCode: "VI", flag: "🇻🇮" },
  { code: "+681", name: "Wallis and Futuna", isoCode: "WF", flag: "🇼🇫" },
  { code: "+967", name: "Yemen", isoCode: "YE", flag: "🇾🇪" },
  { code: "+260", name: "Zambia", isoCode: "ZM", flag: "🇿🇲" },
  { code: "+263", name: "Zimbabwe", isoCode: "ZW", flag: "🇿🇼" },
];
